version: '3.8'
services:
    authkit-db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
        volumes:
            - authkit_data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    authkit_data:
